import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const PrivacyPolicy = () => {
    return (
        <div className="min-h-screen bg-gray-50 font-sans flex flex-col">
            <Navbar />

            <main className="flex-grow pt-32 pb-16 container mx-auto px-6 max-w-4xl">
                <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12 border border-gray-100 text-gray-600">
                    <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>

                    <div className="prose prose-lg max-w-none space-y-6">
                        <p className="text-sm text-gray-400 uppercase tracking-wider font-semibold">Last Updated: 20 February 2026</p>

                        <p>
                            Welcome to EzAuction ("we," "our," or "us"). Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your information when you use our website and auction services available at <a href="https://ezauction.online" className="text-primary hover:underline">https://ezauction.online</a>.
                        </p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">1. Information We Collect</h2>
                        <p>We collect only the information necessary to provide and operate our auction services, including:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Name and team name</li>
                            <li>Player details (name, photo, base price, etc.)</li>
                            <li>Usernames and login credentials generated by admin</li>
                            <li>Auction-related data (bids, team details, auction results)</li>
                            <li>Any images, text, or data uploaded during auction setup</li>
                        </ul>
                        <p>We do NOT collect sensitive personal data like bank account details, passwords of your personal accounts, or government IDs.</p>
                        <p>Payments are made externally via UPI and we do not store your payment credentials.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">2. How We Use Your Information</h2>
                        <p>We use collected data to:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Provide and operate auction services</li>
                            <li>Create and manage auction events</li>
                            <li>Allow bidding and team management</li>
                            <li>Provide technical support</li>
                            <li>Improve our platform</li>
                        </ul>
                        <p>We do not sell your personal data.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">3. Data Sharing</h2>
                        <p>We do not sell or rent your data.</p>
                        <p>Your data may be visible to other participants of the same auction, including:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Player details</li>
                            <li>Team details</li>
                            <li>Auction results</li>
                        </ul>
                        <p>This is essential for auction functionality.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">4. Data Storage and Security</h2>
                        <p>We take reasonable steps to protect your data from:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Unauthorized access</li>
                            <li>Loss</li>
                            <li>Misuse</li>
                        </ul>
                        <p>However, no online platform is 100% secure.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">5. Data Retention</h2>
                        <p>We may retain auction data even after auction completion for:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Record keeping</li>
                            <li>Service improvement</li>
                            <li>Legal protection</li>
                        </ul>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">6. User Uploaded Content</h2>
                        <p>Users may upload content such as:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Player photos</li>
                            <li>Player names</li>
                            <li>Team names</li>
                        </ul>
                        <p>You are responsible for the content you upload.</p>
                        <p>We reserve the right to remove any content without notice.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">7. Children's Privacy</h2>
                        <p>Our services are intended for tournament organizers and participants.</p>
                        <p>We do not knowingly collect personal data from children under 13.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">8. Your Rights</h2>
                        <p>We reserve the right to:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Modify or delete data</li>
                            <li>Suspend accounts</li>
                            <li>Refuse service</li>
                        </ul>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">9. Changes to Privacy Policy</h2>
                        <p>We may update this policy anytime.</p>

                        <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">10. Contact Us</h2>
                        <p>For any questions, contact:</p>
                        <p><strong>+91 7697544446</strong></p>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
};

export default PrivacyPolicy;
